version: '3'

includes:
  dev: ./taskfiles/dev.yaml
  build: ./taskfiles/build.yaml

tasks:
  default:
    - task -a

  setup:
    cmds:
      - curl https://get.volta.sh | bash
      - volta install node
      - volta install pnpm

  install:
    source: package.json
    generates:
      - pnpm-lock.yaml
    cmds:
      - echo "Installing package.json deps"
      - pnpm install

  build:
    deps: [clean, install]
    cmds:
      - task build:default

  clean:
    cmds:
      - rm -rf ./dist
      - mkdir ./dist

  format:
    sources:
      - src/_includes/**/*.{njk}
      - src/css/**/*.css
    generates:
      - dist/css/*.css
      - dist/*.html
    deps:
      - lint
      - prettier

  lint:
    sources:
      - src/_includes/**/*.{njk}
      - src/css/**/*.css

    cmds:
      - pnpm stylelint src/css/**/*.css --fix

  prettier:
    sources:
      - src/_includes/**/*.{njk}
      - src/css/**/*.css
    cmds:
      - pnpm prettier ./ --write

  utopia:
    cmds:
      - node utopia.local/src/index.js
      - pnpm prettier src/design-tokens/
