version: '3'

includes:
  assets: ./assets.yaml

tasks:
  default:
    cmds:
      - task dev:start

  start:
    deps: [assets, postcss, serve]

  serve:
    cmds:
      - pnpm eleventy --serve
    daemon: true
    silent: false

  postcss:
    cmds:
      - pnpm postcss src/css/global.css -o dist/css/global.css --watch
    daemon: true
    silent: false
