name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.token }}
      - name: Run Taskfile - Deploy
        run: task deploy
      - name: Deploy to Production
        uses: actions/deploy-pages@v2
        with:
          github_token: ${{ secrets.token }}
          branch: gh-pages
          folder: dist
